version: "3.9"
services:
    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./:/app

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./:/app
